name: ProjectKorraItems
version: '1.0-SNAPSHOT'
main: projectkorra.items.projectKorraItems.ProjectKorraItems
api-version: '1.21'
load: STARTUP
authors: [ RyanDusty, StrangeOne101, Manu585 ]
description: ProjectKorra Items adds custom equipment which connects with ProjectKorra to modify and enhance bending abilities.
website: projectkorra.com
